---
- name: jetpack install
  become: yes
  apt:
    state: present
    name:
      - nvidia-jetpack
  register: version

- name: add CUDA to PATH
  lineinfile:
    dest: ~/.bashrc
    line: export PATH=/usr/local/cuda-10.0/bin:$PATH

- name: add CUDA to LIBRARY PATH
  lineinfile:
    dest: ~/.bashrc
    line: export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
